/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.4 and the Signal Processing Toolbox 6.22.
 * Generated on: 14-Nov-2016 23:37:33
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 51
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2014b/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 51;
const int16_T B[51] = {
       24,     30,     40,     55,     75,    103,    139,    184,    237,
      299,    370,    448,    534,    625,    719,    816,    912,   1006,
     1096,   1179,   1253,   1317,   1368,   1406,   1429,   1437,   1429,
     1406,   1368,   1317,   1253,   1179,   1096,   1006,    912,    816,
      719,    625,    534,    448,    370,    299,    237,    184,    139,
      103,     75,     55,     40,     30,     24
};
